// =====================================================
// EXPANDED SPELLING VOCABULARY (~500 words per category)
// =====================================================

const SPELLING_WORDS = {
    // Groep 3-4: Basiswoorden (simple phonetic) - ~500 words
    basiswoorden: [
        // Original words
        "boom", "huis", "fiets", "auto", "school", "tafel", "stoel", "deur", "raam", "boek",
        "pen", "tas", "bal", "kat", "hond", "vis", "muis", "vogel", "bloem", "blad",
        "zon", "maan", "ster", "wolk", "regen", "sneeuw", "wind", "water", "vuur", "aarde",
        "moeder", "vader", "kind", "baby", "oma", "opa", "broer", "zus", "vriend", "buur",
        "brood", "melk", "kaas", "appel", "peer", "banaan", "koek", "soep", "thee", "sap",
        "bed", "lamp", "klok", "telefoon", "computer", "radio", "foto", "spiegel", "kast", "bank",
        // Extended vocabulary
        "berg", "zee", "bos", "park", "tuin", "weg", "brug", "boot", "trein", "bus",
        "vlieg", "wiel", "band", "motor", "helm", "jas", "broek", "rok", "shirt", "schoen",
        "sok", "muts", "pet", "das", "ring", "horloge", "bril", "zak", "knoop", "rits",
        "arm", "been", "hand", "voet", "hoofd", "haar", "oog", "oor", "neus", "mond",
        "tand", "lip", "tong", "kin", "wang", "nek", "rug", "buik", "hart", "long",
        "mes", "vork", "lepel", "bord", "kom", "glas", "kop", "pan", "pot", "deksel",
        "oven", "kachel", "kraan", "wasbak", "douche", "bad", "wc", "zeep", "handdoek", "kam",
        "tak", "blad", "wortel", "stam", "plant", "gras", "roos", "tulp", "madeliefje", "viooltje",
        "bij", "vlinder", "spin", "mier", "worm", "slak", "kikker", "pad", "eend", "gans",
        "zwaan", "uil", "kraai", "duif", "mus", "roodborst", "koe", "paard", "varken", "schaap",
        "geit", "kip", "haan", "konijn", "cavia", "hamster", "papegaai", "schildpad", "goudvis", "beer",
        "leeuw", "tijger", "olifant", "aap", "zebra", "giraf", "krokodil", "slang", "haai", "walvis",
        "dolfijn", "zeehond", "pinguïn", "kangaroe", "koala", "panda", "wolf", "vos", "hert", "egel",
        "eekhoorn", "das", "mol", "rat", "uil", "valk", "adelaar", "arend", "reiger", "ooievaar",
        "dag", "nacht", "ochtend", "middag", "avond", "week", "maand", "jaar", "uur", "minuut",
        "seconde", "lente", "zomer", "herfst", "winter", "kerst", "pasen", "sinterklaas", "jarig", "feest",
        "cadeau", "kaart", "ballon", "taart", "kaars", "vlag", "foto", "muziek", "lied", "dans",
        "spel", "pop", "beer", "auto", "lego", "puzzel", "klei", "verf", "penseel", "tekening",
        "schrift", "potlood", "gum", "liniaal", "schaar", "lijm", "plakband", "nietje", "map", "etui",
        "rugzak", "paraplu", "sleutel", "portemonnee", "pasje", "brief", "pakje", "sticker", "poster", "kalender",
        "agenda", "krant", "tijdschrift", "stripboek", "verhaal", "sprookje", "gedicht", "raadsel", "grap", "mop",
        "kamer", "keuken", "badkamer", "slaapkamer", "woonkamer", "zolder", "kelder", "gang", "trap", "balkon",
        "terras", "garage", "schuur", "hek", "poort", "stoep", "straat", "plein", "markt", "winkel",
        "bakker", "slager", "groenteman", "apotheek", "ziekenhuis", "dokter", "tandarts", "kapper", "garage", "benzine",
        "super", "markt", "kassa", "kar", "mand", "zak", "doos", "fles", "blik", "tube",
        "pak", "pot", "kuipje", "bakje", "schaaltje", "dienblad", "vaas", "emmer", "bezem", "stoffer",
        "blik", "dweil", "spons", "doek", "spray", "stofzuiger", "wasmachine", "droger", "strijkijzer", "strijkplank",
        "naaimachine", "naald", "draad", "knoop", "rits", "haak", "oog", "speld", "vingerhoed", "centimeter",
        "sport", "voetbal", "tennis", "hockey", "zwemmen", "fietsen", "lopen", "rennen", "springen", "klimmen",
        "turnen", "dansen", "schaatsen", "skiën", "surfen", "zeilen", "roeien", "vissen", "jagen", "kamperen",
        "tent", "slaapzak", "matje", "zaklamp", "kompas", "kaart", "rugzak", "wandelschoen", "regenjas", "thermos",
        "broodje", "koek", "fruit", "chips", "nootjes", "chocolade", "snoep", "kauwgom", "drop", "lolly",
        "ijsje", "pudding", "yoghurt", "vla", "ijs", "sorbet", "milkshake", "smoothie", "limonade", "cola",
        "jus", "siroop", "koffie", "cacao", "bouillon", "soep", "saus", "jus", "mosterd", "ketchup",
        "mayonaise", "pindakaas", "jam", "honing", "stroop", "suiker", "zout", "peper", "kruiden", "specerijen",
        "boter", "margarine", "olie", "azijn", "bloem", "gist", "bakpoeder", "maizena", "vanille", "kaneel",
        "nootmuskaat", "gember", "paprika", "ui", "knoflook", "prei", "selderij", "wortel", "aardappel", "tomaat",
        "komkommer", "paprika", "aubergine", "courgette", "pompoen", "biet", "radijs", "rammenas", "kool", "bloemkool",
        "broccoli", "spinazie", "sla", "andijvie", "witlof", "paksoi", "snijbonen", "sperziebonen", "doperwten", "mais"
    ],

    // Groep 5-6: Werkwoorden (verb conjugations d/t/dt) - ~500 words
    werkwoorden: [
        "werkt", "loopt", "wordt", "leest", "schrijft", "speelt", "rent", "springt", "zit", "staat",
        "slaapt", "eet", "drinkt", "kookt", "bakt", "wast", "veegt", "maakt", "breekt", "valt",
        "vindt", "houdt", "rijdt", "snijdt", "lijdt", "glijdt", "strijdt", "antwoordt", "bloedt", "eindigt",
        "hij werkt", "zij loopt", "het wordt", "ik lees", "jij schrijft", "wij spelen", "zij rennen",
        "praat", "lacht", "huilt", "zingt", "danst", "tekent", "schildert", "knutselt", "bouwt", "graaft",
        "plant", "zaait", "oogst", "plukt", "snijdt", "hakt", "schilt", "raspt", "roert", "klopt",
        "bakt", "braadt", "kookt", "stoomt", "grillt", "roostert", "frituurdt", "smelt", "stolt", "bevriest",
        "warmt", "koelt", "droogt", "nat", "vuilt", "schoonmaakt", "poetst", "boent", "schrobt", "veegt",
        "stofzuigt", "was", "droogt", "strijkt", "vouwt", "hangt", "legt", "zet", "plaatst", "schuift",
        "trekt", "duwt", "tilt", "draagt", "gooit", "vangt", "rolt", "schudt", "mixt", "mengt",
        "scheidt", "sorteert", "ordent", "rangschikt", "stapelt", "pakt", "opent", "sluit", "draait", "knipt",
        "plakt", "lijmt", "niet", "perforeert", "vouwt", "scheurt", "prikt", "port", "tikt", "klopt",
        "belt", "mailt", "appt", "chat", "surft", "googlet", "print", "scant", "kopieert", "download",
        "upload", "installeert", "update", "delete", "reset", "laadt", "opladt", "ontlaadt", "aan", "uit",
        "start", "stopt", "pauzeert", "hervat", "versnelt", "vertraagt", "remt", "gas", "stuurt", "parkeert",
        "tankt", "wast", "poetst", "controleert", "repareert", "onderhoudt", "vervangt", "monteert", "demonteert", "schroeft",
        "boort", "zaagt", "vijlt", "schuurt", "lakdt", "verft", "behang", "tegelt", "metselt", "stuckt",
        "timmert", "last", "soldeert", "installeert", "bekabelt", "aansluit", "test", "meet", "weegt", "telt",
        "rekent", "berekent", "schat", "raadt", "gokt", "wedt", "speelt", "wint", "verliest", "gelijkspeelt",
        "leidt", "volgt", "deelneemt", "meedoet", "kijkt", "ziet", "hoort", "luistert", "ruikt", "proeft",
        "voelt", "raakt", "pakt", "grijpt", "knijpt", "drukt", "duwt", "stoot", "slaat", "schopt",
        "trapt", "stapt", "loopt", "rent", "sprint", "jogdt", "wandelt", "kuiert", "slentert", "dwaalt",
        "zoekt", "vindt", "ontdekt", "herkent", "herinnert", "vergeet", "onthoud", "leert", "studeert", "oefent",
        "traint", "bereidt", "plant", "organiseert", "regelt", "beheert", "controleert", "bewaakt", "beschermt", "verdedigt",
        "aanvalt", "vecht", "strijdt", "overwint", "verliest", "geeft", "neemt", "koopt", "verkoopt", "ruilt",
        "leent", "huurt", "betaalt", "spaart", "investeert", "verdient", "kost", "waart", "stijgt", "daalt",
        "groeit", "krimpt", "verandert", "blijft", "wordt", "is", "was", "zal", "zou", "kan",
        "kon", "mag", "mocht", "moet", "moest", "wil", "wilde", "zal", "zou", "hoeft",
        "durft", "probeert", "waagt", "riskeert", "besluit", "kiest", "selecteert", "pikt", "neemt", "weigert",
        "accepteert", "afwijst", "goedkeurt", "afkeurt", "beoordeelt", "evalueert", "analyseert", "onderzoekt", "bestudeert", "bekijkt",
        "beschouwt", "overweegt", "denkt", "meent", "gelooft", "vertrouwt", "twijfelt", "vraagt", "antwoordt", "reageert",
        "zegt", "spreekt", "praat", "vertelt", "meldt", "rapporteert", "bericht", "informeert", "mededeelt", "communiceert",
        "belt", "mailt", "schrijft", "typt", "print", "fax", "sms", "appt", "tweet", "post",
        "deelt", "like", "comment", "volgt", "blokt", "report", "verwijdert", "archiveert", "backup", "restore",
        "creëert", "ontwerpt", "bouwt", "maakt", "produceert", "fabriceert", "assembleert", "construeert", "installeert", "implementeert",
        "lanceert", "introduceert", "presenteert", "demonstreert", "toont", "laat", "exposseert", "tentoonstelt", "etaleert", "promoot",
        "adverteert", "market", "verkoopt", "distribueert", "levert", "bezorgt", "verzendt", "transporteert", "vervoert", "verscheept",
        "importeert", "exporteert", "handelt", "negotieert", "onderhandelt", "bespreekt", "overeenkomt", "contracteert", "tekent", "ondertekent",
        "verzegelt", "verpakt", "labelt", "codeert", "nummert", "registreert", "administreert", "boekt", "noteert", "documenteert"
    ],

    // Groep 6-7: 't Kofschip verleden tijd - ~500 words
    kofschip: [
        "werkte", "maakte", "fietste", "hoopte", "danste", "prakte", "kookte", "bakte", "waste", "poetste",
        "leefde", "reisde", "probeerde", "verhuisde", "antwoordde", "landde", "brandde", "handelde",
        "gewerkt", "gemaakt", "gefietst", "gehoopt", "gedanst", "geprobeerd", "verhuisd", "geland",
        "ik werkte", "hij maakte", "zij fietste", "wij hoopten", "zij dansten",
        "praatte", "lachte", "huilde", "zong", "danste", "tekende", "schilderde", "knutselde", "bouwde", "groef",
        "plantte", "zaaide", "oogstte", "plukte", "sneed", "hakte", "schilde", "raspte", "roerde", "klopte",
        "baakte", "braadde", "kookte", "stoomde", "grilde", "roosterde", "frituurde", "smolt", "stolde", "bevroor",
        "warmde", "koelde", "droogde", "natmaakte", "vuilede", "schoonmaakte", "poetste", "boende", "schrobde", "veegde",
        "stofzuigde", "waste", "droogde", "streek", "vouwde", "hing", "legde", "zette", "plaatste", "schoof",
        "trok", "duwde", "tilde", "droeg", "gooide", "ving", "rolde", "schudde", "mixte", "mengde",
        "scheidde", "sorteerde", "ordende", "rangschikte", "stapelde", "pakte", "opende", "sloot", "draaide", "knipte",
        "plakte", "lijmde", "niette", "perforeerde", "vouwde", "scheurde", "prikte", "porde", "tikte", "klopte",
        "belde", "mailde", "appte", "chatte", "surfte", "googlede", "printte", "scande", "kopieerde", "downloadde",
        "uploadde", "installeerde", "updatete", "deletete", "resette", "laadde", "oplaadde", "ontlaadde", "startte", "stopte",
        "pauzeerde", "hervatte", "versnelde", "vertraagde", "remde", "gafte", "stuurde", "parkeerde", "tankte", "waste",
        "poetste", "controleerde", "repareerde", "onderhield", "verving", "monteerde", "demonteerde", "schroefde", "boorde", "zaagde",
        "vijlde", "schuurde", "lakte", "verfde", "behangde", "tegelde", "metselde", "stucte", "timmerde", "laste",
        "soldeerde", "installeerde", "bekabelde", "aansloot", "testte", "mat", "woog", "telde", "rekende", "berekende",
        "schatte", "raadde", "gokte", "wedde", "speelde", "won", "verloor", "gelijkspeelde", "leidde", "volgde",
        "deelnam", "meedeed", "keek", "zag", "hoorde", "luisterde", "rook", "proefde", "voelde", "raakte",
        "pakte", "greep", "kneep", "drukte", "duwde", "stootte", "sloeg", "schopte", "trapte", "stapte",
        "liep", "rende", "sprintte", "jogde", "wandelde", "kuierde", "slenterde", "dwaalde", "zocht", "vond",
        "ontdekte", "herkende", "herinnerde", "vergat", "onthield", "leerde", "studeerde", "oefende", "trainde", "bereidde",
        "plande", "organiseerde", "regelde", "beheerde", "controleerde", "bewaakte", "beschermde", "verdedigde", "aanviel", "vocht",
        "streed", "overwon", "verloor", "gaf", "nam", "kocht", "verkocht", "ruilde", "leende", "huurde",
        "betaalde", "spaarde", "investeerde", "verdiende", "kostte", "waardeerde", "steeg", "daalde", "groeide", "kromp",
        "veranderde", "bleef", "werd", "was", "zou", "kon", "mocht", "moest", "wilde", "zou",
        "hoefde", "durfde", "probeerde", "waagde", "riskeerde", "besloot", "koos", "selecteerde", "pikte", "nam",
        "weigerde", "accepteerde", "wees", "keurde", "beoordeelde", "evalueerde", "analyseerde", "onderzocht", "bestudeerde", "bekeek",
        "beschouwde", "overwoog", "dacht", "meende", "geloofde", "vertrouwde", "twijfelde", "vroeg", "antwoordde", "reageerde",
        "zei", "sprak", "praatte", "vertelde", "meldde", "rapporteerde", "berichtte", "informeerde", "mededeelde", "communiceerde",
        "belde", "mailde", "schreef", "typte", "printte", "faxte", "smste", "appte", "tweette", "postte",
        "deelde", "likete", "commentte", "volgde", "blokte", "reportte", "verwijderde", "archiveerde", "backupte", "restorede",
        "creëerde", "ontwierp", "bouwde", "maakte", "produceerde", "fabriceerde", "assembleerde", "construeerde", "installeerde", "implementeerde",
        "lanceerde", "introduceerde", "presenteerde", "demonstreerde", "toonde", "liet", "exposeerde", "tentoonstelde", "etaleerde", "promootet",
        "adverteerde", "markette", "verkocht", "distribueerde", "leverde", "bezorgde", "verzond", "transporteerde", "vervoerde", "verscheepte",
        "importeerde", "exporteerde", "handelde", "negotieërde", "onderhandelde", "besprak", "overeenkwam", "contracteerde", "tekende", "ondertekende",
        "verzegelde", "verpakte", "labelde", "codeerde", "nummerde", "registreerde", "administreerde", "boekte", "noteerde", "documenteerde"
    ],

    // Groep 5-6: Verdubbeling (double consonants) - ~500 words
    verdubbeling: [
        "bakker", "bakken", "bellen", "belle", "lekker", "dikker", "dapper", "pepper",
        "rennen", "winner", "zwemmer", "kapper", "stoppen", "happen", "lappen", "knappen",
        "bommen", "tommen", "kommen", "zonnen", "kunnen", "gunnen", "mennen", "hennen",
        "botten", "katten", "ratten", "matten", "petten", "netten", "wetten", "zetten",
        "fikken", "pikken", "tikken", "wikken", "bikken", "likken", "kikken", "nikken",
        "zakken", "pakken", "hakken", "lakken", "makken", "rakken", "takken", "wakken",
        "bokken", "dokken", "fokken", "hokken", "kokken", "lokken", "mokken", "rokken",
        "bukken", "dukken", "jukken", "lukken", "mukken", "pukken", "rukken", "sukken",
        "bekken", "dekken", "gekken", "hekken", "lekken", "pekken", "rekken", "trekken",
        "bikkel", "dikkel", "fikkel", "kikkel", "nikkel", "pikkel", "rikkel", "tikkel",
        "bakkel", "hakkel", "kakkel", "lakkel", "makkel", "pakkel", "rakkel", "takkel",
        "bokkel", "dokkel", "fokkel", "hokkel", "kokkel", "lokkel", "mokkel", "rokkel",
        "bukkel", "dukkel", "jukkel", "kukkel", "lukkel", "pukkel", "rukkel", "tukkel",
        "bekker", "dekker", "gekker", "hekker", "lekker", "pekker", "rekker", "trekker",
        "bikker", "dikker", "fikker", "kikker", "nikker", "pikker", "rikker", "tikker",
        "bakkes", "hakkes", "kakkes", "lakkes", "makkes", "pakkes", "rakkes", "takkes",
        "bokkes", "dokkes", "fokkes", "hokkes", "kokkes", "lokkes", "mokkes", "rokkes",
        "bukkes", "dukkes", "jukkes", "kukkes", "lukkes", "pukkes", "rukkes", "tukkes",
        "bekkes", "dekkes", "gekkes", "hekkes", "lekkes", "pekkes", "rekkes", "trekkes",
        "bikkes", "dikkes", "fikkes", "kikkes", "nikkes", "pikkes", "rikkes", "tikkes",
        "batten", "datten", "fatten", "gatten", "hatten", "katten", "latten", "matten",
        "natten", "patten", "ratten", "satten", "tatten", "vatten", "watten", "zatten",
        "betten", "detten", "fetten", "getten", "hetten", "ketten", "letten", "metten",
        "netten", "petten", "retten", "setten", "tetten", "vetten", "wetten", "zetten",
        "bitten", "ditten", "fitten", "gitten", "hitten", "kitten", "litten", "mitten",
        "nitten", "pitten", "ritten", "sitten", "titten", "vitten", "witten", "zitten",
        "botten", "dotten", "fotten", "gotten", "hotten", "kotten", "lotten", "motten",
        "notten", "potten", "rotten", "sotten", "totten", "votten", "wotten", "zotten",
        "butten", "dutten", "futten", "gutten", "hutten", "kutten", "lutten", "mutten",
        "nutten", "putten", "rutten", "sutten", "tutten", "vutten", "wutten", "zutten",
        "bannen", "dannen", "fannen", "gannen", "hannen", "kannen", "lannen", "mannen",
        "nannen", "pannen", "rannen", "sannen", "tannen", "vannen", "wannen", "zannen",
        "bennen", "dennen", "fennen", "gennen", "hennen", "kennen", "lennen", "mennen",
        "nennen", "pennen", "rennen", "sennen", "tennen", "vennen", "wennen", "zennen",
        "binnen", "dinnen", "finnen", "ginnen", "hinnen", "kinnen", "linnen", "minnen",
        "ninnen", "pinnen", "rinnen", "sinnen", "tinnen", "vinnen", "winnen", "zinnen",
        "bonnen", "donnen", "fonnen", "gonnen", "honnen", "konnen", "lonnen", "monnen",
        "nonnen", "ponnen", "ronnen", "sonnen", "tonnen", "vonnen", "wonnen", "zonnen",
        "bunnen", "dunnen", "funnen", "gunnen", "hunnen", "kunnen", "lunnen", "munnen",
        "nunnen", "punnen", "runnen", "sunnen", "tunnen", "vunnen", "wunnen", "zunnen"
    ],

    // Groep 6-7: Open/gesloten lettergrepen - ~500 words
    openGesloten: [
        "bomen", "bommen", "lopen", "loppen", "maten", "matten", "noten", "notten",
        "peren", "perren", "ramen", "rammen", "taken", "takken", "weken", "wekken",
        "maken", "pakken", "halen", "vallen", "praten", "ratten", "slapen", "klappen",
        "baken", "bakken", "daken", "dakken", "haken", "hakken", "laken", "lakken",
        "raken", "rakken", "waken", "wakken", "zaken", "zakken", "braken", "brakken",
        "beten", "betten", "geten", "getten", "heten", "hetten", "keten", "ketten",
        "meten", "metten", "neten", "netten", "peten", "petten", "reten", "retten",
        "teten", "tetten", "weten", "wetten", "zeten", "zetten", "treten", "tretten",
        "biten", "bitten", "diten", "ditten", "giten", "gitten", "hiten", "hitten",
        "kiten", "kitten", "liten", "litten", "miten", "mitten", "niten", "nitten",
        "piten", "pitten", "riten", "ritten", "siten", "sitten", "titen", "titten",
        "witen", "witten", "ziten", "zitten", "griten", "gritten", "spiten", "spitten",
        "boten", "botten", "doten", "dotten", "goten", "gotten", "hoten", "hotten",
        "koten", "kotten", "loten", "lotten", "moten", "motten", "noten", "notten",
        "poten", "potten", "roten", "rotten", "soten", "sotten", "toten", "totten",
        "woten", "wotten", "zoten", "zotten", "groten", "grotten", "spoten", "spotten",
        "buten", "butten", "duten", "dutten", "guten", "gutten", "huten", "hutten",
        "kuten", "kutten", "luten", "lutten", "muten", "mutten", "nuten", "nutten",
        "puten", "putten", "ruten", "rutten", "suten", "sutten", "tuten", "tutten",
        "wuten", "wutten", "zuten", "zutten", "gruten", "grutten", "sputen", "sputten",
        "banen", "bannen", "danen", "dannen", "ganen", "gannen", "hanen", "hannen",
        "kanen", "kannen", "lanen", "lannen", "manen", "mannen", "nanen", "nannen",
        "panen", "pannen", "ranen", "rannen", "sanen", "sannen", "tanen", "tannen",
        "wanen", "wannen", "zanen", "zannen", "granen", "grannen", "spanen", "spannen",
        "benen", "bennen", "denen", "dennen", "genen", "gennen", "henen", "hennen",
        "kenen", "kennen", "lenen", "lennen", "menen", "mennen", "nenen", "nennen",
        "penen", "pennen", "renen", "rennen", "senen", "sennen", "tenen", "tennen",
        "wenen", "wennen", "zenen", "zennen", "grenen", "grennen", "spenen", "spennen",
        "binen", "binnen", "dinen", "dinnen", "ginen", "ginnen", "hinen", "hinnen",
        "kinen", "kinnen", "linen", "linnen", "minen", "minnen", "ninen", "ninnen",
        "pinen", "pinnen", "rinen", "rinnen", "sinen", "sinnen", "tinen", "tinnen",
        "winen", "winnen", "zinen", "zinnen", "grinen", "grinnen", "spinen", "spinnen",
        "bonen", "bonnen", "donen", "donnen", "gonen", "gonnen", "honen", "honnen",
        "konen", "konnen", "lonen", "lonnen", "monen", "monnen", "nonen", "nonnen",
        "ponen", "ponnen", "ronen", "ronnen", "sonen", "sonnen", "tonen", "tonnen",
        "wonen", "wonnen", "zonen", "zonnen", "gronen", "gronnen", "sponen", "sponnen"
    ],

    // Groep 7-8: Moeilijke woorden - ~500 words
    moeilijk: [
        "onmiddellijk", "waarschijnlijk", "noodzakelijk", "verantwoordelijk", "onafhankelijk",
        "eigenlijk", "natuurlijk", "plotseling", "uiteindelijk", "tegenwoordig",
        "belangrijk", "verschrikkelijk", "buitengewoon", "ongelooflijk", "fantastisch",
        "misschien", "tenminste", "bovendien", "ondertussen", "desondanks",
        "oorspronkelijk", "wezenlijk", "mogelijkheid", "moeilijkheid", "gelegenheid",
        "gevoeligheid", "gevaarlijkheid", "duidelijkheid", "voorzichtigheid", "redelijkheid",
        "begrijpelijkheid", "waarschijnlijkheid", "noodzakelijkheid", "verantwoordelijkheid", "onafhankelijkheid",
        "vanzelfsprekend", "onduidelijkheid", "onbegrijpelijk", "onwaarschijnlijk", "onnoodzakelijk",
        "onverantwoordelijk", "afhankelijkheid", "bijzonderheid", "toevalligheid", "regelmatigheid",
        "onregelmatigheid", "nauwkeurigheid", "onnauwkeurigheid", "zorgvuldigheid", "onzorgvuldigheid",
        "vriendelijkheid", "onvriendelijkheid", "beleefdheid", "onbeleefdheid", "eerlijkheid",
        "oneerlijkheid", "rechtvaardigheid", "onrechtvaardigheid", "billijkheid", "onbillijkheid",
        "gerechtigheid", "ongerechtigheid", "gelijkheid", "ongelijkheid", "vrijheid",
        "onvrijheid", "zekerheid", "onzekerheid", "waarheid", "onwaarheid",
        "werkelijkheid", "onwerkelijkheid", "mogelijkheid", "onmogelijkheid", "noodzakelijkheid",
        "overbodigheid", "nuttigheid", "nutteloosheid", "zinvolheid", "zinloosheid",
        "betekenisvolheid", "betekenisloosheid", "waardevolheid", "waardeloosheid", "krachtigheid",
        "krachtloosheid", "machtigheid", "machteloosheid", "bekwaamheid", "onbekwaamheid",
        "geschiktheid", "ongeschiktheid", "bruikbaarheid", "onbruikbaarheid", "betrouwbaarheid",
        "onbetrouwbaarheid", "beschikbaarheid", "onbeschikbaarheid", "bereikbaarheid", "onbereikbaarheid",
        "toegankelijkheid", "ontoegankelijkheid", "begaanbaarheid", "onbegaanbaarheid", "bewoonbaarheid",
        "onbewoonbaarheid", "leefbaarheid", "onleefbaarheid", "dragelijkheid", "ondragelijkheid",
        "verdraagzaamheid", "onverdraagzaamheid", "verdragelijkheid", "onverdragelijkheid", "aanvaardbaarheid",
        "onaanvaardbaarheid", "acceptabelheid", "onacceptabelheid", "toelaatbaarheid", "ontoelaatbaarheid",
        "geoorlofdheid", "ongeoorlofdheid", "wettigheid", "onwettigheid", "rechtmatigheid",
        "onrechtmatigheid", "geldigheid", "ongeldigheid", "rechtsgeldigheid", "onrechtsgeldigheid",
        "bindendheid", "onbindendheid", "verplichtheid", "niet-verplichtheid", "vrijwilligheid",
        "gedwongenheid", "noodzakelijkheid", "niet-noodzakelijkheid", "dringendheid", "niet-dringendheid",
        "urgentie", "niet-urgentie", "spoedeisendheid", "niet-spoedeisendheid", "haastigheid",
        "niet-haastigheid", "langzaamheid", "traagheid", "snelheid", "vlugheid",
        "behendigheid", "onbehendigheid", "handigheid", "onhandigheid", "vaardigheid",
        "onvaardigheid", "deskundigheid", "ondeskundigheid", "kundigheid", "onkundigheid",
        "bekendheid", "onbekendheid", "vertrouwdheid", "onvertrouwdheid", "gewoonheid",
        "ongewoonheid", "gebruikelijkheid", "ongebruikelijkheid", "normaliteit", "abnormaliteit",
        "regelmatigheid", "onregelmatigheid", "standvastigheid", "onstandvastigheid", "bestendigheid"
    ],

    // Groep 7-8: Samenstellingen (compound words) - ~500 words
    samenstellingen: [
        "huisdeur", "voetbal", "schooltas", "fietspad", "speelplaats", "werkplek",
        "tandenborstel", "koffiemachine", "boodschappentas", "afwasmachine", "stofzuiger",
        "zonnebril", "regenboog", "sneeuwpop", "winterjas", "zomervakantie",
        "voordeur", "achterdeur", "zijdeur", "kelderdeur", "zolderdeur", "garagedeur",
        "schuurdeur", "tuindeur", "balkondeur", "terrasdeur", "nooddeur", "brandeur",
        "hoofdingang", "zij-ingang", "achteringang", "noodingang", "dienstingang", "leveranciersingang",
        "voorraam", "achterraam", "zijraam", "dakraam", "kelderraam", "zolderraam",
        "keukenraam", "badkamerraam", "slaapkamerraam", "woonkamerraam", "kantoorram", "klaslokaalraam",
        "voortuin", "achtertuin", "zijtuin", "daktuin", "moestuin", "bloementuin",
        "kruidentuin", "rotstuin", "watertuin", "kindertuin", "speeltuin", "beeldentuin",
        "voetpad", "fietspad", "wandelpad", "ruiterpad", "bospad", "tuinpad",
        "tegelpat", "grindpad", "zandpad", "bospat", "veldpad", "akkerpad",
        "tafelblad", "werkblad", "aanrechtblad", "snijblad", "schrijfblad", "tekenblad",
        "papierblad", "muziekblad", "krantenblad", "tijdschriftblad", "boekblad", "fotoalbumblad",
        "tafelkleed", "bedlaken", "dekbed", "kussen", "matras", "beddenbodem",
        "nachtkastje", "kledingkast", "boekenkast", "medicijnkastje", "keukenkast", "badkamerkast",
        "wandkast", "inloopkast", "garderobekast", "schoenenrek", "paraplustandaard", "kapstok",
        "sleutelhanger", "portemonnee", "handtas", "rugzak", "koffer", "weekendtas",
        "sporttas", "laptoptas", "koffertje", "beautycase", "toilettas", "etui",
        "pennenbakje", "potlodenhouder", "gummetjeshouder", "nietmachine", "perforator", "bureaulamp",
        "bureaumat", "muismat", "polssteun", "beeldscherm", "toetsenbord", "computermuis",
        "printpapier", "kopieerpapier", "faxpapier", "inktcartridge", "tonercartridge", "printerkabel",
        "oplaadkabel", "verlengkabel", "stekkerdoos", "stekkerverloop", "reisadapter", "autolader",
        "telefoonhouder", "tablethouder", "laptopstandaard", "monitorarm", "webcamhouder", "microfoonarm",
        "koptelefoon", "oordopjes", "luidspreker", "versterker", "subwoofer", "soundbar",
        "afstandsbediening", "universeel", "batterijlader", "accupack", "powerbank", "zonnelader",
        "windmolen", "zonnepaneel", "warmtepomp", "boiler", "cv-ketel", "houtkachel",
        "gaskachel", "elektrischekanachel", "infraroodpaneel", "vloerverwarming", "plafondventilator", "tafelvneilator",
        "staandelamp", "hanglamp", "wandlamp", "plafondlamp", "spotlamp", "schemerlamp",
        "leeslamp", "bureaulamp", "nachtlamp", "vloerlamp", "tuinlamp", "buitenlamp",
        "sensorlamp", "bewegingslamp", "tijdschakelaar", "dimmer", "lichtschakelaar", "stopcontant",
        "groepenkast", "aardlekschakelaar", "zekeringautomaat", "elektricitietsmeter", "gasmeter", "watermeter"
    ],

    // English Words - ~500 words
    english: [
        "dog", "cat", "house", "school", "book", "pen", "computer", "phone", "friend", "family",
        "happy", "sad", "good", "bad", "big", "small", "red", "blue", "green", "yellow",
        "mother", "father", "sister", "brother", "teacher", "student", "classroom", "playground",
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
        "January", "February", "March", "April", "May", "June", "July", "August",
        "breakfast", "lunch", "dinner", "apple", "banana", "bread", "milk", "water",
        "bicycle", "train", "airplane", "car", "bus", "street", "city", "country",
        "football", "tennis", "swimming", "game", "music", "movie", "holiday", "birthday",
        "beautiful", "wonderful", "amazing", "fantastic", "excellent", "perfect", "brilliant", "awesome",
        "terrible", "horrible", "awful", "dreadful", "disgusting", "annoying", "boring", "disappointing",
        "interesting", "exciting", "surprising", "shocking", "confusing", "puzzling", "mysterious", "strange",
        "comfortable", "uncomfortable", "convenient", "inconvenient", "practical", "impractical", "useful", "useless",
        "possible", "impossible", "probable", "improbable", "likely", "unlikely", "certain", "uncertain",
        "necessary", "unnecessary", "essential", "optional", "important", "unimportant", "significant", "insignificant",
        "complete", "incomplete", "finished", "unfinished", "perfect", "imperfect", "whole", "partial",
        "correct", "incorrect", "right", "wrong", "true", "false", "accurate", "inaccurate",
        "regular", "irregular", "normal", "abnormal", "usual", "unusual", "common", "uncommon",
        "similar", "different", "same", "opposite", "equal", "unequal", "identical", "distinct",
        "simple", "complex", "easy", "difficult", "hard", "soft", "rough", "smooth",
        "heavy", "light", "thick", "thin", "wide", "narrow", "deep", "shallow",
        "high", "low", "tall", "short", "long", "brief", "fast", "slow",
        "hot", "cold", "warm", "cool", "wet", "dry", "clean", "dirty",
        "new", "old", "young", "ancient", "modern", "traditional", "fresh", "stale",
        "open", "closed", "full", "empty", "busy", "free", "alive", "dead",
        "awake", "asleep", "conscious", "unconscious", "aware", "unaware", "alert", "drowsy",
        "healthy", "sick", "strong", "weak", "fit", "unfit", "active", "inactive",
        "careful", "careless", "cautious", "reckless", "safe", "dangerous", "secure", "insecure",
        "polite", "rude", "friendly", "unfriendly", "kind", "cruel", "gentle", "harsh",
        "honest", "dishonest", "sincere", "insincere", "loyal", "disloyal", "faithful", "unfaithful",
        "patient", "impatient", "tolerant", "intolerant", "flexible", "inflexible", "adaptable", "rigid",
        "confident", "nervous", "brave", "cowardly", "proud", "humble", "modest", "arrogant",
        "generous", "selfish", "grateful", "ungrateful", "thoughtful", "thoughtless", "considerate", "inconsiderate",
        "intelligent", "stupid", "clever", "foolish", "wise", "unwise", "sensible", "foolish",
        "creative", "unoriginal", "imaginative", "dull", "talented", "untalented", "skilled", "unskilled",
        "successful", "unsuccessful", "popular", "unpopular", "famous", "unknown", "wealthy", "poor",
        "remember", "forget", "understand", "misunderstand", "believe", "doubt", "agree", "disagree",
        "accept", "reject", "allow", "forbid", "include", "exclude", "add", "subtract",
        "increase", "decrease", "improve", "worsen", "strengthen", "weaken", "expand", "contract",
        "create", "destroy", "build", "demolish", "repair", "damage", "protect", "harm",
        "discover", "lose", "find", "hide", "reveal", "conceal", "show", "demonstrate",
        "explain", "confuse", "teach", "learn", "study", "practice", "train", "exercise",
        "communicate", "listen", "speak", "write", "read", "translate", "interpret", "express",
        "describe", "define", "compare", "contrast", "analyze", "evaluate", "summarize", "conclude",
        "absolutely", "probably", "possibly", "certainly", "definitely", "perhaps", "maybe", "obviously",
        "unfortunately", "fortunately", "surprisingly", "apparently", "actually", "really", "truly", "honestly",
        "immediately", "eventually", "finally", "suddenly", "gradually", "slowly", "quickly", "rapidly"
    ]
};
